config/routes.rb
Prueba::Application.routes.draw do
  resources :horarios

  resources :materias

  resources :cursos do
   resources :estudiantes
  end
  

  resources :instructores

 

end

app/models/horario.rb
class Horario < ActiveRecord::Base
  attr_accessible :aula, :dia, :hora, :materia_id, :instructor_id, :curso_id

  def self.search(search)
where('aula like ?', "%#{search}%")
end

validates :aula, :presence => true,
:length => { :maximum => 80 }

belongs_to :materia
belongs_to :instructor
belongs_to :curso
end

app/controllers/horarios_controller.rb
class HorariosController < ApplicationController
  helper_method :sort_column, :sort_direction
  def index
    if params[:rs]==nil or (params[:rs] <='0') then
    params[:rs]=3
  end
  @horarios = Horario.order(sort_column + " " + sort_direction).search(params[:search]).page(params[:page]).per_page(params[:rs].to_i)
  respond_to do |format|
  format.html # index.html.erb
  format.xml { render :xml => @horarios }
  end
end

  def show
      @horario = Horario.find(params[:id])
        pdf = HorarioPdf.new(@horario, view_context)
        send_data pdf.render, filename:
        "horario_#{@horario.id}.pdf",
        type: "aplication/pdf"
  end

  def new
      @horario = Horario.new
  end

  def edit
      @horario= Horario.find(params[:id])
  end

  def create
      @horario = Horario.new(params[:horario])
      render :action => :new unless @horario.save
      @horarios = Horario.all
  end

  def update
      @horario = Horario.find(params[:id])
      render :action => :edit unless @horario.update_attributes(params[:horario])
  end

  def destroy
      @horario = Horario.find(params[:id])
      @horario.destroy
      @horarios = Horario.all
  end

   private
  
  def sort_column
    Horario.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/horarios_helper.rb
module HorariosHelper
    def display_base_errors resource
        return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
            messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
            html = <<-HTML
            <div class="alert alert-error alert-block">
            <button type="button" class="close" data-dismiss="alert">&#215;</button>#{messages}
            </div>
            HTML
            html.html_safe
    end
end

app/views/horarios/_form.html.erb
<%= simple_form_for(@horario, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

  <%= f.error_notification %>
  <%= display_base_errors @horario %>

  <%= f.input :dia %>
  <%= f.input :hora %>
  <%= f.input :aula %>

  Instructor:
   <%= f.collection_select :instructor_id, Instructor.all, :id, :nombres, prompt: "Instructor" %>
   
  Materia:
   <%= f.collection_select :materia_id, Materia.all, :id, :nombre, prompt: "Materia" %>

  Curso:
   <%= f.collection_select :curso_id, Curso.all, :id, :nombre, prompt: "Curso" %>

  <div class="form-actions">
    <%= f.submit "guardar", :class => 'btn btn-info' %>
    <%= link_to 'Atras', horarios_path, :class => 'btn btn-inverse' %>
  </div>
<% end %>

app/views/horarios/_horario.html.erb
<tr id=<%= "horario_#{horario.id}" %>>
  <td><%= link_to horario.id, edit_horario_path(horario), :remote => true %></td>
  <td><%= horario.dia %></td>
  <td><%= horario.hora %></td>
  <td><%= horario.aula %></td>
  <td><%= horario.instructor_id %></td>
  <td><%= horario.materia.nombre %></td>
  <td><%= horario.curso.nombre %></td>
  <td>

    <%= link_to  image_tag('ver.gif', :title => "Ver"), horario, :remote => true, :class => 'btn btn-mini btn-info' %>
    <%= link_to image_tag('editar.gif', :title => "Editar"), edit_horario_path(horario), :remote => true,
        :class => 'btn btn-success btn-mini' %>
    <%= link_to image_tag('eliminar.gif', :title => "Eliminar"), horario, 
        :data => { :confirm => 'Esta Seguro?' },
        :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
    <%= link_to 'Pdf', horario_path(horario, :format => 'pdf'), :class => 'btn btn-mini btn-success'%>
  </td>
</tr>

app/views/horarios/_show.html.erb
<%- model_class = Horario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class='horario'>
  <p><%= @horario.id %></p>
  <p><%= @horario.dia %></p>
  <p><%= @horario.hora %></p>
  <p><%= @horario.aula %></p>
</div>

app/views/horarios/create.js.erb
$('table tbody').append("<%= escape_javascript(render @horario) %>")
$.lazybox.close()
$('input#totalregs').attr('value','<%= @horarios.count %>');

app/views/horarios/destroy.js.erb
$("table tr#horario_<%= @horario.id %>").remove();
$('input#totalregs').attr('value','<%= @horarios.count %>');

app/views/horarios/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/horarios/index.html.erb
<br>
<br>
<div class="page-header">
<center><h1>Horarios</h1></center>
</div>
<br />
<br />
<center>
<%= form_tag request.path, :method => 'get' do %>
<%= content_tag :label do %>
Busqueda:
<%= text_field_tag :search, params[:search] %>
<%= submit_tag "Consultar", :aula => nil, :class => 'btn btn-inverse btn-mini' %>
<% end %>
<% end %>
<%= form_tag request.path, :method => 'get' do %>
<%= content_tag :label do %>
Numero de Registros:
<%= text_field_tag :rs, params[:rs] %>
<% end %>
<% end %>
<br />
<br />
<br />
</center>
<table class="table table-striped table-bordered table-condensed pretty">
  <thead>
<tr>
  <th><%= sortable "id" %></th>
  <th><%= sortable "dia" %></th>
  <th><%= sortable "hora" %></th>
  <th><%= sortable "aula" %></th>
  <th><%= sortable "instructor_id" %></th>
  <th><%= sortable "materia_id" %></th>
  <th><%= sortable "curso_id" %></th>
</tr>


  </thead>
  <tbody>
     <%= render @horarios %>
  </tbody>
  <tfoot>
    <tr>
      <td><%= link_to 'Nuevo Horario',   new_horario_path, :class => "btn btn-mini btn-info", :remote => true %></td>
    </tr>
  </tfoot>
</table>
<br />
<br />
<div align="center">
<%= will_paginate @horarios, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
&raquo;' rescue nil%>
</div>
<p>
Total Aprendices :<input type="text"  id="totalregs" class="span1" value="<%= @horarios.total_entries %>" readonly />
</p>

app/views/horarios/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/horarios/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})

app/views/horarios/update.js.erb
$('tr#horario_<%= @horario.id %>').replaceWith("<%= escape_javascript(render @horario) %>")
$.lazybox.close()