config/routes.rb
Prueba::Application.routes.draw do
  resources :horarios

  resources :materias

  resources :cursos do
   resources :estudiantes
  end
  

  resources :instructores

 

end

app/models/curso.rb
class Curso < ActiveRecord::Base
  attr_accessible :nombre, :ficha

  def self.search(search)
where('nombre like ? or ficha like ?', "%#{search}%", "%#{search}")
end

validates :nombre, :presence => true,
:length => { :maximum => 80 }

has_many :estudiantes
has_many :horarios
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  helper_method :sort_column, :sort_direction
  def index
  if (params[:rgs]==nil) or (params[:rgs] <='0') then
    params[:rgs]=3
  end
  @cursos = Curso.order(sort_column + " " + sort_direction).search(params[:search]).page(params[:page]).per_page(params[:rgs].to_i)
  respond_to do |format|
  format.html # index.html.erb
  format.xml { render :xml => @cursos }
  end
end

  def show
        @curso= Curso.find(params[:id])
        pdf = CursoPdf.new(@curso, view_context)
        send_data pdf.render, filename:
        "curso_#{@curso.id}.pdf",
        type: "aplication/pdf"
  end

  def new
      @curso = Curso.new
  end

  def edit
      @curso= Curso.find(params[:id])
  end

  def create
      @curso = Curso.new(params[:curso])
      render :action => :new unless @curso.save
      @cursos = Curso.all
  end

  def update
      @curso = Curso.find(params[:id])
      render :action => :edit unless @curso.update_attributes(params[:curso])
  end

  def destroy
      @curso = Curso.find(params[:id])
      @curso.destroy
      @cursos = Curso.all
  end
  
  private
  
  def sort_column
    Curso.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/cursos_helper.rb
module CursosHelper
    def display_base_errors resource
        return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
            messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
            html = <<-HTML
            <div class="alert alert-error alert-block">
            <button type="button" class="close" data-dismiss="alert">&#215;</button>#{messages}
            </div>
            HTML
            html.html_safe
    end
end

app/views/cursos/_curso.html.erb
<tr id=<%= "curso_#{curso.id}" %>>
  <td><%= link_to curso.id, edit_curso_path(curso), :remote => true %></td>
  <td><%= curso.nombre %></td>
  <td><%= curso.ficha %></td>
  <td>
    
    <%= link_to  image_tag('ver.gif', :title => "Ver"), curso,     :remote => true, :class => 'btn btn-mini btn-info' %>
    <%= link_to image_tag('editar.gif', :title => "Editar"), edit_curso_path(curso), :remote => true,
        :class => 'btn btn-success btn-mini' %>
    <%= link_to image_tag('eliminar.gif', :title => "Eliminar"), curso, 
        :data => { :confirm => 'Esta Seguro?' },
        :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
    <%= link_to  "Estudiantes",curso_estudiantes_path(curso), :class => 'btn btn-mini btn-info' %>
    <%= link_to 'Pdf', curso_path(curso, :format => 'pdf'), :class => 'btn btn-mini btn-success'%>
  </td>
</tr>

app/views/cursos/_form.html.erb
<%= simple_form_for(@curso, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

  <%= f.error_notification %>
  <%= display_base_errors @curso %>

  <%= f.input :nombre %>
  <%= f.input :ficha %>
  
  <div class="form-actions">
    <%= f.submit "guardar", :class => 'btn btn-info' %>
    <%= link_to 'Atras', cursos_path, :class => 'btn btn-inverse' %>
  </div>
<% end %>

app/views/cursos/_show.html.erb
<%- model_class = Curso -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class='curso'>
  <p><%= @curso.id %></p>
  <p><%= @curso.nombre %></p>
  <p><%= @curso.ficha %></p>
  <p id="pdf_link"><%= link_to "Download Invoice (PDF)", curso_path(@curso, :format => "pdf") %></p>
</div>

app/views/cursos/create.js.erb
$('table tbody').append("<%= escape_javascript(render @curso) %>")
$.lazybox.close()
$('input#totalregs').attr('value','<%= @cursos.count %>');

app/views/cursos/destroy.js.erb
$("table tr#curso_<%= @curso.id %>").remove();
$('input#totalregs').attr('value','<%= @cursos.count %>');

app/views/cursos/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/cursos/index.html.erb
<br>
<br>
<div class="page-header">
<center><h1>Cursos</h1></center>
</div>
<br />
<br />
<center>
<%= form_tag request.path, :method => 'get' do %>
<%= content_tag :label do %>
Nombre Curso:
<%= text_field_tag :search, params[:search] %>
<%= submit_tag "Buscar", :name => nil, :class => 'btn btn-inverse btn-mini' %>
<% end %>
<% end %>
<%= form_tag request.path, :method => 'get' do %>
<%= content_tag :label do %>
Numero de Registros:
<%= text_field_tag :rgs, params[:rgs] %>
<%= submit_tag "Consultar", :name => nil, :class => 'btn btn-inverse btn-mini' %>
<% end %>
<% end %>
<br />
<br />
<br />
</center>
<table class="table table-striped table-bordered table-condensed pretty">
  <thead>
<tr>
  <th><%= sortable "id" %></th>
  <th><%= sortable "nombre" %></th>
  <th><%= sortable "ficha" %></th>
</tr>


  </thead>
  <tbody>
     <%= render @cursos %>
  </tbody>
  <tfoot>
    <tr>
      <td><%= link_to 'Nuevo Curso',   new_curso_path, :class => "btn btn-mini btn-success", :remote => true %></td>
    </tr>
  </tfoot>
</table>
<br />
<br />
<div align="center">
<%= will_paginate @cursos, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
&raquo;' rescue nil%>
</div>
<p>
Total Cursos :<input type="text"  id="totalregs" class="span1" value="<%= @cursos.total_entries %>" readonly />
</p>

app/views/cursos/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/cursos/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})

app/views/cursos/update.js.erb
$('tr#curso_<%= @curso.id %>').replaceWith("<%= escape_javascript(render @curso) %>")
$.lazybox.close()