config/routes.rb
Prueba::Application.routes.draw do
  resources :horarios

  resources :materias

  resources :cursos do
   resources :estudiantes
  end
  

  resources :instructores

 

end

app/models/materia.rb
class Materia < ActiveRecord::Base
  attr_accessible :nombre

  def self.search(search)
where('nombre like ?', "%#{search}%")
end

validates :nombre, :presence => true,
:length => { :maximum => 80 }

has_many :horarios
end

app/controllers/materias_controller.rb
class MateriasController < ApplicationController
  helper_method :sort_column, :sort_direction
  def index
  if params[:res]==nil or (params[:res] <='0') then
    params[:res]=3
  end
  @materias = Materia.order(sort_column + " " + sort_direction).search(params[:search]).page(params[:page]).per_page(params[:res].to_i)
  respond_to do |format|
  format.html # index.html.erb
  format.xml { render :xml => @materias }
  end
end

  def show
      @materia = Materia.find(params[:id])
        pdf = MateriaPdf.new(@materia, view_context)
        send_data pdf.render, filename:
        "materia_#{@materia.id}.pdf",
        type: "aplication/pdf"
  end

  def new
      @materia = Materia.new
  end

  def edit
      @materia= Materia.find(params[:id])
  end

  def create
      @materia = Materia.new(params[:materia])
      render :action => :new unless @materia.save
      @materias = Materia.all
  end

  def update
      @materia = Materia.find(params[:id])
      render :action => :edit unless @materia.update_attributes(params[:materia])
  end

  def destroy
      @materia = Materia.find(params[:id])
      @materia.destroy
      @materias = Materia.all
  end
  
  private
  
  def sort_column
    Materia.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/materias_helper.rb
module MateriasHelper
    def display_base_errors resource
        return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
            messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
            html = <<-HTML
            <div class="alert alert-error alert-block">
            <button type="button" class="close" data-dismiss="alert">&#215;</button>#{messages}
            </div>
            HTML
            html.html_safe
    end
end

app/views/materias/_form.html.erb
<%= simple_form_for(@materia, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

  <%= f.error_notification %>
  <%= display_base_errors @materia %>

  <%= f.input :nombre %>
  
  <div class="form-actions">
    <%= f.submit "guardar", :class => 'btn btn-info' %>
    <%= link_to 'Atras', materias_path, :class => 'btn btn-inverse' %>
  </div>
<% end %>

app/views/materias/_materia.html.erb
<tr id=<%= "materia_#{materia.id}" %>>
  <td><%= link_to materia.id, edit_materia_path(materia), :remote => true %></td>
  <td><%= materia.nombre %></td>

  <td>


    <%= link_to  image_tag('ver.gif', :title => "Ver"), materia, :remote => true, :class => 'btn btn-mini btn-info' %>
    <%= link_to image_tag('editar.gif', :title => "Editar"), edit_materia_path(materia), :remote => true,
        :class => 'btn btn-success btn-mini' %>
    <%= link_to image_tag('eliminar.gif', :title => "Eliminar"), materia, 
        :data => { :confirm => 'Esta Seguro?' },
        :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
    <%= link_to 'Pdf', materia_path(materia, :format => 'pdf'), :class => 'btn btn-mini btn-success'%>
  </td>
</tr>

app/views/materias/_show.html.erb
<%- model_class = Materia -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class='materia'>
  <p><%= @materia.id %></p>
  <p><%= @materia.nombre %></p>

</div>

app/views/materias/create.js.erb
$('table tbody').append("<%= escape_javascript(render @materia) %>")
$.lazybox.close()
$('input#totalregs').attr('value','<%= @materias.count %>');

app/views/materias/destroy.js.erb
$("table tr#materia_<%= @materia.id %>").remove();
$('input#totalregs').attr('value','<%= @materias.count %>');

app/views/materias/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/materias/index.html.erb
<br>
<br>
<div class="page-header">
<center><h1>Materias</h1></center>
</div>
<br />
<br />
<center>
<%= form_tag request.path, :method => 'get' do %>
<%= content_tag :label do %>
Nombre Materia:
<%= text_field_tag :search, params[:search] %>
<%= submit_tag "Consultar", :name => nil, :class => 'btn btn-inverse btn-mini' %>
<% end %>
<% end %>
<%= form_tag request.path, :method => 'get' do %>
<%= content_tag :label do %>
Numero de Registros:
<%= text_field_tag :res, params[:res] %>
<% end %>
<% end %>
<br />
<br />
<br />
</center>
<table class="table table-striped table-bordered table-condensed pretty">
  <thead>
<tr>
  <th><%= sortable "id" %></th>
  <th><%= sortable "nombre" %></th>
</tr>


  </thead>
  <tbody>
     <%= render @materias %>
  </tbody>
  <tfoot>
    <tr>
      <td><%= link_to 'Nueva Materia',   new_materia_path, :class => "btn btn-mini btn-info", :remote => true %></td>
    </tr>
  </tfoot>
</table>
<br />
<br />
<div align="center">
<%= will_paginate @materias, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
&raquo;' rescue nil %>
</div>
<p>
Total Materias :<input type="text"  id="totalregs" class="span1" value="<%= @materias.total_entries %>" readonly />
</p>
</p>

app/views/materias/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/materias/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})

app/views/materias/update.js.erb
$('tr#materia_<%= @materia.id %>').replaceWith("<%= escape_javascript(render @materia) %>")
$.lazybox.close()