config/routes.rb
Prueba::Application.routes.draw do
  resources :horarios

  resources :materias

  resources :cursos do
   resources :estudiantes
  end
  

  resources :instructores

 

end

app/models/estudiante.rb
class Estudiante < ActiveRecord::Base
  validates :nombre, :presence => true,
  :length => { :maximum => 80 }

  validates :email, :presence => true,
 :uniqueness => true,
 :format => { :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

validates :cedula, :presence => true,
:length => { :minimum => 6, :maximum => 15 },
:numericality => true

  attr_accessible :cedula, :direccion, :email, :fch_nacimineto, :nombre, :curso_id, :photo
	def self.search(search)
		where('nombre like ? or email like ? or cedula like ? or direccion like ?' , "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
	end

has_attached_file :photo, :styles => { :small => "150x150>" },
                  :url  => "/assets/estudiantes/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/estudiantes/:id/:style/:basename.:extension"

validates_attachment_presence :photo
validates_attachment_size :photo, :less_than => 5.megabytes
validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

belongs_to :curso

end

app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  before_filter :relacion
  helper_method :sort_column, :sort_direction
  def index
  if params[:registros]==nil or (params[:registros] <='0') then
    params[:registros]=3
  end
  @estudiantes = @curso.estudiantes.order(sort_column + " " + sort_direction).search(params[:search]).page(params[:page]).per_page(params[:registros].to_i)
  respond_to do |format|
  format.html # index.html.erb
  format.xml { render :xml => @estudiantes }
  end
end
  def show
      @estudiante = Estudiante.find(params[:id])
        pdf = EstudiantePdf.new(@estudiante, view_context)
        send_data pdf.render, filename:
        "estudiante_#{@estudiante.id}.pdf",
        type: "aplication/pdf"
  end

  def new
      @estudiante = Estudiante.new
  end

  def edit
      @estudiante= Estudiante.find(params[:id])
  end

  def create
      @estudiante = @curso.estudiantes.build(params[:estudiante])
      render :action => :new unless @estudiante.save
      @estudiantes = Estudiante.all
  end

  def update
      @estudiante = Estudiante.find(params[:id])
      render :action => :edit unless @estudiante.update_attributes(params[:estudiante])
  end

  def destroy
      @estudiante = Estudiante.find(params[:id])
      @estudiante.destroy
      @estudiantes = Estudiante.all
  end

  def relacion
  @curso = Curso.find(params[:curso_id])
  @estudiante = Estudiante.find(params[:id]) if params[:id]
  end

   private
  
  def sort_column
    Estudiante.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
    def display_base_errors resource
        return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
            messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
            html = <<-HTML
            <div class="alert alert-error alert-block">
            <button type="button" class="close" data-dismiss="alert">&#215;</button>#{messages}
            </div>
            HTML
            html.html_safe
    end
end

app/views/estudiantes/_estudiante.html.erb
<tr id=<%= "estudiante_#{estudiante.id}" %>>
  <td><%= link_to estudiante.id, edit_curso_estudiante_path(@curso,estudiante), :remote => true %></td>
  <td><%= estudiante.nombre %></td>
  <td><%= estudiante.cedula %></td>
  <td><%= estudiante.email %></td>
  <td><%= estudiante.direccion %></td>
  <td><%= estudiante.fch_nacimineto %></td>

  <td>

    <%= link_to  image_tag('ver.gif', :title => "Ver"), curso_estudiante_path(@curso,estudiante), :remote => true, :class => 'btn btn-mini btn-info' %>
    <%= link_to image_tag('editar.gif', :title => "Editar"), edit_curso_estudiante_path(@curso,estudiante), :remote => true,
        :class => 'btn btn-success btn-mini' %>
    <%= link_to image_tag('eliminar.gif', :title => "Eliminar"), curso_estudiante_path(@curso,estudiante), 
        :data => { :confirm => 'Esta Seguro?' },
        :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
    <%= link_to 'Pdf', curso_estudiante_path(@curso,estudiante, :format => 'pdf'), :class => 'btn btn-mini btn-success'%>
  </td>
</tr>

app/views/estudiantes/_form.html.erb
<%= simple_form_for([@curso, @estudiante], :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

  <%= f.error_notification %>
  <%= display_base_errors @estudiante %>
  <%= f.file_field :photo %>
  <%= f.input :nombre %>
  <%= f.input :cedula %>
  <%= f.input :email %>
  <%= f.input :direccion %>
  <%= f.input :fch_nacimineto %>
  
  <div class="form-actions">
    <%= f.submit "guardar", :class => 'btn btn-info' %>
    <%= link_to 'Atras', curso_estudiantes_path, :class => 'btn btn-inverse' %>
  </div>
<% end %>

app/views/estudiantes/_show.html.erb
<%- model_class = Estudiante -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>
<%= image_tag @estudiante.photo.url(:small) %>
<div class='estudiante'>
  <p><%= @estudiante.id %></p>
  <p><%= @estudiante.nombre %></p>
  <p><%= @estudiante.cedula %></p>
  <p><%= @estudiante.email %></p>
  <p><%= @estudiante.direccion %></p>
  <p><%= @estudiante.fch_nacimineto %><p>

</div>

app/views/estudiantes/create.js.erb
$('table tbody').append("<%= escape_javascript(render @estudiante) %>")
$.lazybox.close()
$('input#totalregs').attr('value','<%= @estudiantes.count %>');

app/views/estudiantes/destroy.js.erb
$("table tr#estudiante_<%= @estudiante.id %>").remove();
$('input#totalregs').attr('value','<%= @estudiantes.count %>');

app/views/estudiantes/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/estudiantes/index.html.erb
<br>
<br>
<div class="page-header">
<center><h1>Estudiantes</h1></center>
</div>
<br />
<br /> 
<center>
<%= form_tag request.path, :method => 'get' do %>
<%= content_tag :label do %>
Nombre Estudiante
<%= text_field_tag :search, params[:search] %>
<%= submit_tag "Consultar", :name => nil, :class => 'btn btn-mini btn-inverse'  %>
<% end %>
<% end %>
<%= form_tag request.path, :method => 'get' do %>
<%= content_tag :label do %>
Numero de Registros
<%= text_field_tag :registros, params[:registros] %>
<% end %>
<% end %>
<br />
<br />
<br /> 
</center>
<table class="table table-striped table-bordered table-condensed pretty">
  
<tr>
  <th><%= sortable "id" %></th>
  <th><%= sortable "nombre" %></th>
  <th><%= sortable "cedula" %></th>
  <th><%= sortable "email" %></th>
  <th><%= sortable "direccion" %></th>
  <th><%= sortable "fecha_nacimiento"  %></th>
</tr>


  </thead>
  <tbody>
     <%= render @estudiantes %>
  </tbody>
  <tfoot>
    <tr>
      <td><%= link_to 'Nuevo Estudiante',   new_curso_estudiante_path, :class => "btn btn-mini btn-info", :remote => true %></td>
    </tr>
  </tfoot>
</table>
<br>
<br>
<%= link_to 'Atras', cursos_path, :class => 'btn btn-small btn-inverse' %>
<br />
<br />
<div align="center">
<%= will_paginate @estudiantes, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
&raquo;' rescue nil%>
</div>
<p>
Total Aprendices :<input type="text"  id="totalregs" class="span1" value="<%= @estudiantes.total_entries %>" readonly />
</p>

app/views/estudiantes/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/estudiantes/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})

app/views/estudiantes/update.js.erb
$('tr#estudiante_<%= @estudiante.id %>').replaceWith("<%= escape_javascript(render @estudiante) %>")
$.lazybox.close()